var myCircle = Circles.create({
  id:                  'circles-1',
  radius:              60,
  value:               80,
  maxValue:            100,
  width:               5,
  text:                function(value){return value + '%';},
  colors:              ['#FFF', '#00bcd4'],
  duration:            400,
  wrpClass:            'circles-wrp',
  textClass:           'circles-text',
  valueStrokeClass:    'circles-valueStroke',
  maxValueStrokeClass: 'circles-maxValueStroke',
  styleWrapper:        true,
  styleText:           true
});
var myCircle = Circles.create({
  id:                  'circles-2',
  radius:              60,
  value:               80,
  maxValue:            100,
  width:               5,
  text:                function(value){return value + '%';},
  colors:              ['#FFF', '#00bcd4'],
  duration:            400,
  wrpClass:            'circles-wrp',
  textClass:           'circles-text',
  valueStrokeClass:    'circles-valueStroke',
  maxValueStrokeClass: 'circles-maxValueStroke',
  styleWrapper:        true,
  styleText:           true
});
var myCircle = Circles.create({
  id:                  'circles-3',
  radius:              60,
  value:               80,
  maxValue:            100,
  width:               5,
  text:                function(value){return value + '%';},
  colors:              ['#FFF', '#00bcd4'],
  duration:            400,
  wrpClass:            'circles-wrp',
  textClass:           'circles-text',
  valueStrokeClass:    'circles-valueStroke',
  maxValueStrokeClass: 'circles-maxValueStroke',
  styleWrapper:        true,
  styleText:           true
});
var myCircle = Circles.create({
  id:                  'circles-4',
  radius:              60,
  value:               80,
  maxValue:            100,
  width:               5,
  text:                function(value){return value + '%';},
  colors:              ['#FFF', '#00bcd4'],
  duration:            400,
  wrpClass:            'circles-wrp',
  textClass:           'circles-text',
  valueStrokeClass:    'circles-valueStroke',
  maxValueStrokeClass: 'circles-maxValueStroke',
  styleWrapper:        true,
  styleText:           true
});
var myCircle = Circles.create({
  id:                  'circles-5',
  radius:              60,
  value:               60,
  maxValue:            100,
  width:               5,
  text:                function(value){return value + '%';},
  colors:              ['#FFF', '#00bcd4'],
  duration:            400,
  wrpClass:            'circles-wrp',
  textClass:           'circles-text',
  valueStrokeClass:    'circles-valueStroke',
  maxValueStrokeClass: 'circles-maxValueStroke',
  styleWrapper:        true,
  styleText:           true
});
var myCircle = Circles.create({
  id:                  'circles-6',
  radius:              60,
  value:               60,
  maxValue:            100,
  width:               5,
  text:                function(value){return value + '%';},
  colors:              ['#FFF', '#00bcd4'],
  duration:            400,
  wrpClass:            'circles-wrp',
  textClass:           'circles-text',
  valueStrokeClass:    'circles-valueStroke',
  maxValueStrokeClass: 'circles-maxValueStroke',
  styleWrapper:        true,
  styleText:           true
});
var myCircle = Circles.create({
  id:                  'circles-7',
  radius:              60,
  value:               60,
  maxValue:            100,
  width:               5,
  text:                function(value){return value + '%';},
  colors:              ['#FFF', '#00bcd4'],
  duration:            400,
  wrpClass:            'circles-wrp',
  textClass:           'circles-text',
  valueStrokeClass:    'circles-valueStroke',
  maxValueStrokeClass: 'circles-maxValueStroke',
  styleWrapper:        true,
  styleText:           true
});
var myCircle = Circles.create({
  id:                  'circles-8',
  radius:              60,
  value:               60,
  maxValue:            100,
  width:               5,
  text:                function(value){return value + '%';},
  colors:              ['#FFF', '#00bcd4'],
  duration:            400,
  wrpClass:            'circles-wrp',
  textClass:           'circles-text',
  valueStrokeClass:    'circles-valueStroke',
  maxValueStrokeClass: 'circles-maxValueStroke',
  styleWrapper:        true,
  styleText:           true
});
var myCircle = Circles.create({
  id:                  'circles-9',
  radius:              60,
  value:               40,
  maxValue:            100,
  width:               5,
  text:                function(value){return value + '%';},
  colors:              ['#FFF', '#00bcd4'],
  duration:            400,
  wrpClass:            'circles-wrp',
  textClass:           'circles-text',
  valueStrokeClass:    'circles-valueStroke',
  maxValueStrokeClass: 'circles-maxValueStroke',
  styleWrapper:        true,
  styleText:           true
});
var myCircle = Circles.create({
  id:                  'circles-10',
  radius:              60,
  value:               60,
  maxValue:            100,
  width:               5,
  text:                function(value){return value + '%';},
  colors:              ['#FFF', '#00bcd4'],
  duration:            400,
  wrpClass:            'circles-wrp',
  textClass:           'circles-text',
  valueStrokeClass:    'circles-valueStroke',
  maxValueStrokeClass: 'circles-maxValueStroke',
  styleWrapper:        true,
  styleText:           true
});
var myCircle = Circles.create({
  id:                  'circles-11',
  radius:              60,
  value:               50,
  maxValue:            100,
  width:               5,
  text:                function(value){return value + '%';},
  colors:              ['#FFF', '#00bcd4'],
  duration:            400,
  wrpClass:            'circles-wrp',
  textClass:           'circles-text',
  valueStrokeClass:    'circles-valueStroke',
  maxValueStrokeClass: 'circles-maxValueStroke',
  styleWrapper:        true,
  styleText:           true
});
var myCircle = Circles.create({
  id:                  'circles-12',
  radius:              60,
  value:               80,
  maxValue:            100,
  width:               5,
  text:                function(value){return value + '%';},
  colors:              ['#FFF', '#00bcd4'],
  duration:            400,
  wrpClass:            'circles-wrp',
  textClass:           'circles-text',
  valueStrokeClass:    'circles-valueStroke',
  maxValueStrokeClass: 'circles-maxValueStroke',
  styleWrapper:        true,
  styleText:           true
});
